# https://taskfile.dev

version: '3'

silent: true

tasks:
  dev:alpine: npm run dev --workspace=packages/alpine
  dev:maska: npm run dev --workspace=packages/maska
  dev:maska-build-watch: npm run build:watch --workspace=packages/maska
  dev:vue: npm run dev --workspace=packages/vue

  code:test: npm run test --workspaces
  code:test-alpine: npm run test --workspace=packages/alpine
  code:coverage: npm run test:coverage --workspaces
  code:lint: npm run lint --workspaces
  code:format: npm run lint:fix --workspaces

  build: npm run build --workspaces
