# https://taskfile.dev

version: '3'

silent: true

tasks:
  dev:maska: npm run dev --workspace=packages/maska
  dev:maska-build-watch: npm run build:watch --workspace=packages/maska
  dev:vue: npm run dev --workspace=packages/vue

  build: npm run build --workspaces

  test: npm run test --workspaces
  coverage: npm run test:coverage --workspaces
